import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePatient1753564909775 implements MigrationInterface {
  name = 'CreatePatient1753564909775';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."Patient_insuranceprovider_enum" AS ENUM('bpjs', 'prudential', 'allianz', 'axa', 'bnilife', 'inhealth', 'fwd', 'sinarmas', 'other')`,
    );
    await queryRunner.query(
      `CREATE TABLE "Patient" ("patientId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "insuranceProvider" "public"."Patient_insuranceprovider_enum", "insurancePolicyNumber" character varying, "userUserId" uuid, CONSTRAINT "REL_820a688cf5537e81bb6df05a48" UNIQUE ("userUserId"), CONSTRAINT "PK_06e559cfedb81de608071295bd7" PRIMARY KEY ("patientId"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ADD "identityNumber" character varying(20) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ADD CONSTRAINT "UQ_001c7ba2ac15c6718fac04e7f50" UNIQUE ("identityNumber")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Patient" ADD CONSTRAINT "FK_820a688cf5537e81bb6df05a48c" FOREIGN KEY ("userUserId") REFERENCES "User"("userId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "Patient" DROP CONSTRAINT "FK_820a688cf5537e81bb6df05a48c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" DROP CONSTRAINT "UQ_001c7ba2ac15c6718fac04e7f50"`,
    );
    await queryRunner.query(`ALTER TABLE "User" DROP COLUMN "identityNumber"`);
    await queryRunner.query(`DROP TABLE "Patient"`);
    await queryRunner.query(
      `DROP TYPE "public"."Patient_insuranceprovider_enum"`,
    );
  }
}
