import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePatientInsurance1754264551692 implements MigrationInterface {
    name = 'CreatePatientInsurance1754264551692'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Patient" DROP CONSTRAINT "FK_820a688cf5537e81bb6df05a48c"`);
        await queryRunner.query(`CREATE TYPE "public"."PatientInsurance_insuranceprovider_enum" AS ENUM('bpjs', 'prudential', 'allianz', 'axa', 'bnilife', 'inhealth', 'fwd', 'sinarmas', 'other')`);
        await queryRunner.query(`CREATE TABLE "PatientInsurance" ("patientInsuranceId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "insuranceProvider" "public"."PatientInsurance_insuranceprovider_enum" NOT NULL, "policyNumber" character varying NOT NULL, "patientId" integer, CONSTRAINT "PK_aa6b0763909740b68c0a99765cc" PRIMARY KEY ("patientInsuranceId"))`);
        await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "insuranceProvider"`);
        await queryRunner.query(`DROP TYPE "public"."Patient_insuranceprovider_enum"`);
        await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "insurancePolicyNumber"`);
        await queryRunner.query(`ALTER TABLE "Patient" DROP CONSTRAINT "REL_820a688cf5537e81bb6df05a48"`);
        await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "userUserId"`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD CONSTRAINT "UQ_fd38098a3964235e38f0223d2aa" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "PatientInsurance" ADD CONSTRAINT "FK_5e9c80d860ab95f054323c2cf2b" FOREIGN KEY ("patientId") REFERENCES "Patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD CONSTRAINT "FK_fd38098a3964235e38f0223d2aa" FOREIGN KEY ("userId") REFERENCES "User"("userId") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Patient" DROP CONSTRAINT "FK_fd38098a3964235e38f0223d2aa"`);
        await queryRunner.query(`ALTER TABLE "PatientInsurance" DROP CONSTRAINT "FK_5e9c80d860ab95f054323c2cf2b"`);
        await queryRunner.query(`ALTER TABLE "Patient" DROP CONSTRAINT "UQ_fd38098a3964235e38f0223d2aa"`);
        await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD "userUserId" uuid`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD CONSTRAINT "REL_820a688cf5537e81bb6df05a48" UNIQUE ("userUserId")`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD "insurancePolicyNumber" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."Patient_insuranceprovider_enum" AS ENUM('bpjs', 'prudential', 'allianz', 'axa', 'bnilife', 'inhealth', 'fwd', 'sinarmas', 'other')`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD "insuranceProvider" "public"."Patient_insuranceprovider_enum"`);
        await queryRunner.query(`DROP TABLE "PatientInsurance"`);
        await queryRunner.query(`DROP TYPE "public"."PatientInsurance_insuranceprovider_enum"`);
        await queryRunner.query(`ALTER TABLE "Patient" ADD CONSTRAINT "FK_820a688cf5537e81bb6df05a48c" FOREIGN KEY ("userUserId") REFERENCES "User"("userId") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
