import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddEmployee1758355748882 implements MigrationInterface {
  name = 'AddEmployee1758355748882';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "Employee" ("employeeId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "startDate" date NOT NULL, "retirementDate" date, CONSTRAINT "PK_9973b9c95adf07d027b2a719a07" PRIMARY KEY ("employeeId"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "Employee"`);
  }
}
