import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddDoctor1758944103252 implements MigrationInterface {
  name = 'AddDoctor1758944103252';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."DoctorSchedule_day_enum" AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')`,
    );
    await queryRunner.query(
      `CREATE TABLE "DoctorSchedule" ("doctorScheduleId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "day" "public"."DoctorSchedule_day_enum" NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "doctorDoctorId" uuid, CONSTRAINT "PK_48c3704087c1a31fb8bd7db1c15" PRIMARY KEY ("doctorScheduleId"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Doctor" ("doctorId" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, CONSTRAINT "PK_fbb152e99c81843d4455055d6e3" PRIMARY KEY ("doctorId"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "DoctorSchedule" ADD CONSTRAINT "FK_4a27ab52eece53fd6baeb5978da" FOREIGN KEY ("doctorDoctorId") REFERENCES "Doctor"("doctorId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "DoctorSchedule" DROP CONSTRAINT "FK_4a27ab52eece53fd6baeb5978da"`,
    );
    await queryRunner.query(`DROP TABLE "Doctor"`);
    await queryRunner.query(`DROP TABLE "DoctorSchedule"`);
    await queryRunner.query(`DROP TYPE "public"."DoctorSchedule_day_enum"`);
  }
}
