import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddNurse1759139068352 implements MigrationInterface {
  name = 'AddNurse1759139068352';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."NurseSchedule_day_enum" AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')`,
    );
    await queryRunner.query(
      `CREATE TABLE "NurseSchedule" ("nurseScheduleId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "day" "public"."NurseSchedule_day_enum" NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "nurseNurseId" uuid, CONSTRAINT "PK_9a3d6da1d2f22af9d5f65f8229a" PRIMARY KEY ("nurseScheduleId"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Nurse" ("nurseId" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, CONSTRAINT "PK_3f94677dfea9d7a45d00bcd6cc9" PRIMARY KEY ("nurseId"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "NurseSchedule" ADD CONSTRAINT "FK_8c93ad16e21585b4238f674c2d8" FOREIGN KEY ("nurseNurseId") REFERENCES "Nurse"("nurseId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "NurseSchedule" DROP CONSTRAINT "FK_8c93ad16e21585b4238f674c2d8"`,
    );
    await queryRunner.query(`DROP TABLE "Nurse"`);
    await queryRunner.query(`DROP TABLE "NurseSchedule"`);
    await queryRunner.query(`DROP TYPE "public"."NurseSchedule_day_enum"`);
  }
}
