import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateIds1760369831187 implements MigrationInterface {
  name = 'UpdateIds1760369831187';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "Nurse" DROP CONSTRAINT "FK_66fbef54b9119193f102fb61fdf"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Nurse" DROP CONSTRAINT "UQ_66fbef54b9119193f102fb61fdf"`,
    );
    await queryRunner.query(`ALTER TABLE "Nurse" DROP COLUMN "employeeId"`);
    await queryRunner.query(`ALTER TABLE "Nurse" ADD "employeeId" uuid`);
    await queryRunner.query(
      `ALTER TABLE "Nurse" ADD CONSTRAINT "UQ_66fbef54b9119193f102fb61fdf" UNIQUE ("employeeId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" DROP CONSTRAINT "FK_5e9c80d860ab95f054323c2cf2b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" DROP COLUMN "patientId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" ADD "patientId" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" DROP CONSTRAINT "FK_ceca0c75fde8f7ec420063d1475"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Patient" DROP CONSTRAINT "PK_06e559cfedb81de608071295bd7"`,
    );
    await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "patientId"`);
    await queryRunner.query(
      `ALTER TABLE "Patient" ADD "patientId" uuid NOT NULL DEFAULT uuid_generate_v4()`,
    );
    await queryRunner.query(
      `ALTER TABLE "Patient" ADD CONSTRAINT "PK_06e559cfedb81de608071295bd7" PRIMARY KEY ("patientId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" DROP COLUMN "patientId"`,
    );
    await queryRunner.query(`ALTER TABLE "Appointment" ADD "patientId" uuid`);
    await queryRunner.query(
      `ALTER TABLE "Doctor" DROP CONSTRAINT "FK_872c2af744448c72e262ab3bff6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Doctor" DROP CONSTRAINT "UQ_872c2af744448c72e262ab3bff6"`,
    );
    await queryRunner.query(`ALTER TABLE "Doctor" DROP COLUMN "employeeId"`);
    await queryRunner.query(`ALTER TABLE "Doctor" ADD "employeeId" uuid`);
    await queryRunner.query(
      `ALTER TABLE "Doctor" ADD CONSTRAINT "UQ_872c2af744448c72e262ab3bff6" UNIQUE ("employeeId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Employee" DROP CONSTRAINT "PK_9973b9c95adf07d027b2a719a07"`,
    );
    await queryRunner.query(`ALTER TABLE "Employee" DROP COLUMN "employeeId"`);
    await queryRunner.query(
      `ALTER TABLE "Employee" ADD "employeeId" uuid NOT NULL DEFAULT uuid_generate_v4()`,
    );
    await queryRunner.query(
      `ALTER TABLE "Employee" ADD CONSTRAINT "PK_9973b9c95adf07d027b2a719a07" PRIMARY KEY ("employeeId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Nurse" ADD CONSTRAINT "FK_66fbef54b9119193f102fb61fdf" FOREIGN KEY ("employeeId") REFERENCES "Employee"("employeeId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" ADD CONSTRAINT "FK_5e9c80d860ab95f054323c2cf2b" FOREIGN KEY ("patientId") REFERENCES "Patient"("patientId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" ADD CONSTRAINT "FK_ceca0c75fde8f7ec420063d1475" FOREIGN KEY ("patientId") REFERENCES "Patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Doctor" ADD CONSTRAINT "FK_872c2af744448c72e262ab3bff6" FOREIGN KEY ("employeeId") REFERENCES "Employee"("employeeId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "Doctor" DROP CONSTRAINT "FK_872c2af744448c72e262ab3bff6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" DROP CONSTRAINT "FK_ceca0c75fde8f7ec420063d1475"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" DROP CONSTRAINT "FK_5e9c80d860ab95f054323c2cf2b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Nurse" DROP CONSTRAINT "FK_66fbef54b9119193f102fb61fdf"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Employee" DROP CONSTRAINT "PK_9973b9c95adf07d027b2a719a07"`,
    );
    await queryRunner.query(`ALTER TABLE "Employee" DROP COLUMN "employeeId"`);
    await queryRunner.query(
      `ALTER TABLE "Employee" ADD "employeeId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Employee" ADD CONSTRAINT "PK_9973b9c95adf07d027b2a719a07" PRIMARY KEY ("employeeId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Doctor" DROP CONSTRAINT "UQ_872c2af744448c72e262ab3bff6"`,
    );
    await queryRunner.query(`ALTER TABLE "Doctor" DROP COLUMN "employeeId"`);
    await queryRunner.query(`ALTER TABLE "Doctor" ADD "employeeId" integer`);
    await queryRunner.query(
      `ALTER TABLE "Doctor" ADD CONSTRAINT "UQ_872c2af744448c72e262ab3bff6" UNIQUE ("employeeId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Doctor" ADD CONSTRAINT "FK_872c2af744448c72e262ab3bff6" FOREIGN KEY ("employeeId") REFERENCES "Employee"("employeeId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" DROP COLUMN "patientId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" ADD "patientId" integer`,
    );
    await queryRunner.query(
      `ALTER TABLE "Patient" DROP CONSTRAINT "PK_06e559cfedb81de608071295bd7"`,
    );
    await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "patientId"`);
    await queryRunner.query(
      `ALTER TABLE "Patient" ADD "patientId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Patient" ADD CONSTRAINT "PK_06e559cfedb81de608071295bd7" PRIMARY KEY ("patientId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Appointment" ADD CONSTRAINT "FK_ceca0c75fde8f7ec420063d1475" FOREIGN KEY ("patientId") REFERENCES "Patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" DROP COLUMN "patientId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" ADD "patientId" integer`,
    );
    await queryRunner.query(
      `ALTER TABLE "PatientInsurance" ADD CONSTRAINT "FK_5e9c80d860ab95f054323c2cf2b" FOREIGN KEY ("patientId") REFERENCES "Patient"("patientId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Nurse" DROP CONSTRAINT "UQ_66fbef54b9119193f102fb61fdf"`,
    );
    await queryRunner.query(`ALTER TABLE "Nurse" DROP COLUMN "employeeId"`);
    await queryRunner.query(`ALTER TABLE "Nurse" ADD "employeeId" integer`);
    await queryRunner.query(
      `ALTER TABLE "Nurse" ADD CONSTRAINT "UQ_66fbef54b9119193f102fb61fdf" UNIQUE ("employeeId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "Nurse" ADD CONSTRAINT "FK_66fbef54b9119193f102fb61fdf" FOREIGN KEY ("employeeId") REFERENCES "Employee"("employeeId") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }
}
