export enum EmployeeDepartment {
  FrontOffice = 'FrontOffice',
  BackOffice = 'BackOffice',
  Obgyn = 'Obgyn',
  Pediatric = 'Pediatric',
  ENT = 'ENT',
  Surgery = 'Surgery',
  Radiology = 'Radiology',
  Cardiology = 'Cardiology',
  Neurology = 'Neurology',
  Orthopedics = 'Orthopedics',
  Urology = 'Urology',
  Ophthalmology = 'Ophthalmology',
  EmergencyDepartment = 'EmergencyDepartment',
  Pharmacy = 'Pharmacy',
  ICU = 'ICU',
  Inpatient = 'Inpatient',
}
