export enum EmployeeDepartment {
  FrontOffice = 'frontoffice',
  BackOffice = 'backoffice',
  Obgyn = 'obgyn',
  Pediatric = 'pediatric',
  ENT = 'ent',
  Surgery = 'surgery',
  Radiology = 'radiology',
  Cardiology = 'cardiology',
  Neurology = 'neurology',
  Orthopedics = 'orthopedics',
  Urology = 'urology',
  Ophthalmology = 'ophthalmology',
  EmergencyDepartment = 'emergencydepartment',
  Pharmacy = 'pharmacy',
  ICU = 'icu',
  Inpatient = 'inpatient',
}
